AmadeusNet/Models/Flights/FlightSearchModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AmadeusNet.Models.Flights
{
    public class FlightSearchModel
    {
        public FlightSearchModel()
        {
            Origin = "BOS";
            Destination = "LON";

            DepartureDate = DateTime.Now.AddDays(1);
            ReturnDate = DateTime.Now.AddDays(3);

            NumberAdults = 1;
            NumberChildren = 0;
            NumberInfants = 0;

            IsReturn = false;
        }

        [Required(ErrorMessage = "Origin is required")]
        public string Origin { get; set; }
        [Required(ErrorMessage = "Destination is required")]
        public string Destination { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DepartureDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ReturnDate { get; set; }

        [Required(ErrorMessage = "Number of adults is required")]
        [Range(1, int.MaxValue)]
        public int NumberAdults { get; set; }

        [Required(ErrorMessage = "Number of children is required")]
        [Range(0, int.MaxValue)]
        public int NumberChildren { get; set; }

        [Required(ErrorMessage = "Number of infants is required")]
        [Range(0, int.MaxValue)]
        public int NumberInfants { get; set; }

        public int NumberOfResults => 10;

        public string Currency => "EUR";

        public bool IsReturn { get; set; }

        public override bool Equals(object obj)
        {
            return base.Equals(obj);
        }

        protected bool Equals(FlightSearchModel other)
        {
            return string.Equals(Origin, other.Origin) && string.Equals(Destination, other.Destination) && DepartureDate.Equals(other.DepartureDate) && ReturnDate.Equals(other.ReturnDate) && NumberAdults == other.NumberAdults && NumberChildren == other.NumberChildren && NumberInfants == other.NumberInfants && IsReturn == other.IsReturn;
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = (Origin != null ? Origin.GetHashCode() : 0);
                hashCode = (hashCode*397) ^ (Destination != null ? Destination.GetHashCode() : 0);
                hashCode = (hashCode*397) ^ DepartureDate.GetHashCode();
                hashCode = (hashCode*397) ^ ReturnDate.GetHashCode();
                hashCode = (hashCode*397) ^ NumberAdults;
                hashCode = (hashCode*397) ^ NumberChildren;
                hashCode = (hashCode*397) ^ NumberInfants;
                hashCode = (hashCode*397) ^ IsReturn.GetHashCode();
                return hashCode;
            }
        }


        /// <summary>
        /// Creates cache key based on class name and hashcode
        /// </summary>
        public string GetCacheKey => $"{this.GetType().Name}_{this.GetHashCode()}";
    }
}

AmadeusNet/Models/Flights/RootResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace AmadeusNet.Models.Flights
{
    /// <summary>
    /// Generated from JSON
    /// </summary>
    public class RootResult
    {
        public string currency { get; set; }
        public IList<Result> results { get; set; }
    }

    public class Origin
    {
        public string airport { get; set; }
        public string terminal { get; set; }
    }

    public class Destination
    {
        public string airport { get; set; }
        public string terminal { get; set; }
    }

    public class BookingInfo
    {
        public string travel_class { get; set; }
        public string booking_code { get; set; }
        public int seats_remaining { get; set; }
    }

    public class Flight
    {
        public string departs_at { get; set; }
        public string arrives_at { get; set; }
        public Origin origin { get; set; }
        public Destination destination { get; set; }
        public string marketing_airline { get; set; }
        public string operating_airline { get; set; }
        public string flight_number { get; set; }
        public string aircraft { get; set; }
        public BookingInfo booking_info { get; set; }
    }

    public class Outbound
    {
        public IList<Flight> flights { get; set; }
    }

    public class Inbound
    {
        public IList<Flight> flights { get; set; }
    }

    public class Itinerary
    {
        public Outbound outbound { get; set; }
        public Inbound inbound { get; set; }
    }

    public class PricePerAdult
    {
        public string total_fare { get; set; }
        public string tax { get; set; }
    }

    public class Restrictions
    {
        public bool refundable { get; set; }
        public bool change_penalties { get; set; }
    }

    public class Fare
    {
        public string total_price { get; set; }
        public PricePerAdult price_per_adult { get; set; }
        public Restrictions restrictions { get; set; }
    }

    public class Result
    {
        public IList<Itinerary> itineraries { get; set; }
        public Fare fare { get; set; }
    }
}

AmadeusNet/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using AmadeusNet.Models.Flights;
using log4net;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;

namespace AmadeusNet.Controllers
{
    
    public class FlightsController : Controller
    {
        // GET: Flights
        public ActionResult Index()
        {
            var model = new FlightSearchModel();
            return View(model);
        }


        /// <summary>
        /// Post action for searching Amadeus Sandbox for Low-fare flights
        /// </summary>
        /// <param name="filter">Search parameters</param>
        /// <returns></returns>
        [HttpPost]
        public PartialViewResult Search(FlightSearchModel filter)
        {
            try
            {
                RootResult model = null;
                //try to find object in cache
                if (ModelState.IsValid)
                {
                   
                    var cached = (RootResult) WebCache.Get(filter.GetCacheKey);
                    if (cached != null)
                    {
                        return PartialView("FlightResultsPartial", cached);
                    }

                    
                    using (
                        var client =
                            new HttpClient(new HttpClientHandler
                            {
                                AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate,
                            }))
                    {

                        NameValueCollection queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);

                        queryString["apikey"] = Config.ApiKey;
                        queryString["origin"] = filter.Origin;
                        queryString["destination"] = filter.Destination;
                        queryString["adults"] = filter.NumberAdults.ToString();
                        queryString["children"] = filter.NumberChildren.ToString();
                        queryString["departure_date"] = filter.DepartureDate.ToString("yyyy-MM-dd");
                        if (filter.IsReturn)
                            queryString["return_date"] = filter.ReturnDate.ToString("yyyy-MM-dd");
                        queryString["number_of_results"] = filter.NumberOfResults.ToString();
                        queryString["currency"] = filter.Currency;
                        queryString["infants"] = filter.NumberInfants.ToString();

                        client.BaseAddress = new Uri(Config.ApiUrl);
                        HttpResponseMessage response = client.GetAsync("?" + queryString).Result;
                        response.EnsureSuccessStatusCode();
                        string result = response.Content.ReadAsStringAsync().Result;

                        //deserializing Response
                        model = JsonConvert.DeserializeObject<RootResult>(result);

                        //cache object, defult expiration policy
                        if (model != null)
                        {
                            WebCache.Set(filter.GetCacheKey, model);
                        }
                    }
                }

                return PartialView("FlightResultsPartial", model);
            }
            catch (Exception ex)
            {
                ViewBag.Exception = ex.Message;
                LogManager.GetLogger(typeof(FlightsController)).Fatal(ex.Message);
                return PartialView("FlightResultsPartial", null);
            }
           
        }
    }
}

AmadeusNet/Views/Flights/FlightResultsPartial.cshtml
@model AmadeusNet.Models.Flights.RootResult

@{
    if (Model == null)
    {
        <div class="alert alert-info">
            @if (ViewBag.Exception != null)
            {
                @Html.Raw(ViewBag.Exception);
            }
            else
            {
                @:<strong>Info!</strong>No results.
            }
           

        </div>
    }
    else
    {
        var first = true;
        foreach (var result in Model.results)
        {
            <div class="card card-block @(@first ? "card-outline-primary" : "")">
                <h3 class="card-title">@result.fare.total_price&nbsp;@Model.currency</h3>
                 @{ first = false; }
                <div class="card-text">

                    <strong>Outbound</strong>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>From</th>
                                    <th>To</th>
                                    <th>Departs at</th>
                                    <th>Arrives at</th>
                                    <th>Airline</th>
                                    <th>Class</th>
                                    <th>Flight</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var flight in result.itineraries[0].outbound.flights)
                                {
                                    <tr>
                                        <td>
                                            @flight.origin.airport @if (flight.origin.terminal != null)
                                            {<span>(terminal&nbsp;@flight.origin.terminal)</span>}
                                        </td>
                                        <td>
                                            @flight.destination.airport @if (flight.destination.terminal != null)
                                            {<span>(terminal&nbsp;@flight.destination.terminal)</span>}
                                        </td>
                                        <td>@DateTime.Parse(flight.departs_at)</td>
                                        <td>@DateTime.Parse(flight.arrives_at)</td>
                                        <td>@flight.operating_airline</td>
                                        <td>@flight.booking_info.travel_class</td>
                                        <td>@flight.flight_number</td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                    

                    @if (result.itineraries[0].inbound != null)
                    {
                        <strong>Inbound</strong>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>From</th>
                                        <th>To</th>
                                        <th>Departs at</th>
                                        <th>Arrives at</th>
                                        <th>Airline</th>
                                        <th>Class</th>
                                        <th>Flight</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var flight in result.itineraries[0].inbound.flights)
                                    {
                                        <tr>
                                            <td>
                                                @flight.origin.airport @if (flight.origin.terminal != null)
                                                {<span>(terminal&nbsp;@flight.origin.terminal)</span>}
                                            </td>
                                            <td>
                                                @flight.destination.airport @if (flight.destination.terminal != null)
                                                {<span>(terminal&nbsp;@flight.destination.terminal)</span>}
                                            </td>
                                            <td>@DateTime.Parse(flight.departs_at)</td>
                                            <td>@DateTime.Parse(flight.arrives_at)</td>
                                            <td>@flight.operating_airline</td>
                                            <td>@flight.booking_info.travel_class</td>
                                            <td>@flight.flight_number</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>
                    }

                </div>
            </div>
        }
    }

}

AmadeusNet/Views/Flights/Index.cshtml
@model AmadeusNet.Models.Flights.FlightSearchModel
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-md-3">
        @using (Ajax.BeginForm("Search", "Flights", new AjaxOptions() {UpdateTargetId = "resultSection", HttpMethod = "Post", InsertionMode = InsertionMode.Replace, LoadingElementId = "spinner"}))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-group">
                <label for="origin">Origin airport (IATA code)</label>
                @Html.TextBoxFor(m => m.Origin, new {@class = "form-control", @id = "origin", @placeholder = "Origin airport"})
                @Html.ValidationMessageFor(model => model.Origin)
            </div>
            <div class="form-group">
                <label for="destination">Destination airport (IATA code)</label>
                @Html.TextBoxFor(m => m.Destination, new {@class = "form-control", @id = "destination", @placeholder = "Destination airport"})
                @Html.ValidationMessageFor(model => model.Destination)
            </div>
            <div class="form-group">
                <label for="departureDate">Departure date</label>
                @Html.TextBoxFor(m => m.DepartureDate, "{0:yyyy-MM-dd}", new {@type = "date", @class = "form-control", @id = "departureDate", @placeholder = "Departure date"})
                @Html.ValidationMessageFor(model => model.DepartureDate)
            </div>

            <div class="form-check">
                <label class="form-check-label">
                    @Html.CheckBoxFor(m => m.IsReturn, new {@type = "checkbox", @class = "form-check-input", @id = "returnFlight"})
                    Return flight
                </label>
            </div>



            <div class="form-group" id="returnDateGroup" style="@(@Model.IsReturn ? "" : "display:none")">
                <label for="returnDate">Return date</label>
                @Html.TextBoxFor(m => m.ReturnDate, "{0:yyyy-MM-dd}", new {@type = "date", @class = "form-control", @id = "returnDate", @placeholder = "Return date"})
                @Html.ValidationMessageFor(model => model.ReturnDate)
            </div>



            <div class="form-group">
                <label for="numberAdults">Number of adults</label>
                @Html.TextBoxFor(m => m.NumberAdults, new {@type = "number", @min = "1", @class = "form-control", @id = "numberAdults", @placeholder = "Number of adults"})
                @Html.ValidationMessageFor(model => model.NumberAdults)
            </div>

            <div class="form-group">
                <label for="numberChildren">Number of children</label>
                @Html.TextBoxFor(m => m.NumberChildren, new {@type = "number", @min = "0", @class = "form-control", @id = "numberChildren", @placeholder = "Number of children"})
                @Html.ValidationMessageFor(model => model.NumberChildren)
            </div>

            <div class="form-group">
                <label for="numberInfants">Number of infants</label>
                @Html.TextBoxFor(m => m.NumberInfants, new { @type = "number", @min = "0", @class = "form-control", @id = "numberInfants", @placeholder = "Number of infants" })
                @Html.ValidationMessageFor(model => model.NumberInfants)
            </div>

            <div class="form-group">
                <input class="btn btn-success" type="submit" value="Search"/>
            </div>

        }
    </div>
    <div class="col-md-9" id="resultSection">
        <div class="alert alert-info" role="alert">
            <strong>Ready!</strong> Search for flights.
        </div>
    </div>
</div>